import path from 'path';
import fs from 'fs';
import { CleanupRule, ResolvedTargetRoot, CleanupExplanation, ToolchainId } from '../../shared/src/rules.types.js';

export class BaseCleanupRule implements CleanupRule {
  constructor(
    public readonly id: string,
    public readonly version: number,
    public readonly name: string,
    public readonly category: CleanupRule['category'],
    public readonly safetyLevel: CleanupRule['safetyLevel'],
    public readonly defaultSelection: boolean,
    public readonly requiresElevation: boolean,
    public readonly rebuildCost: CleanupRule['rebuildCost'],
    public readonly networkRequiredToRebuild: boolean,
    public readonly targetResolvers: () => string[],
    public readonly explanationDetails: CleanupExplanation,
    public readonly warning?: string,
    public readonly toolchainId?: ToolchainId,
    public readonly relatedToolchains?: ToolchainId[]
  ) {}

  public async resolveTargets(): Promise<ResolvedTargetRoot[]> {
    const rawPaths = this.targetResolvers();
    const results: ResolvedTargetRoot[] = [];

    for (const raw of rawPaths) {
      const canonical = path.resolve(raw).replace(/^[a-z]:/i, m => m.toUpperCase());
      let exists = false;
      try {
        await fs.promises.access(canonical);
        exists = true;
      } catch {
        exists = false;
      }

      results.push({
        ruleId: this.id,
        label: this.name,
        canonicalPath: canonical,
        exists
      });
    }

    return results;
  }

  public explain(): CleanupExplanation {
    return this.explanationDetails;
  }
}

export class RuleRegistry {
  private rules: Map<string, CleanupRule> = new Map();

  constructor() {
    this.registerBuiltinRules();
  }

  private registerBuiltinRules(): void {
    const userProfile = process.env.USERPROFILE || 'C:\\Users\\Default';
    const localAppData = process.env.LOCALAPPDATA || path.join(userProfile, 'AppData', 'Local');
    const appData = process.env.APPDATA || path.join(userProfile, 'AppData', 'Roaming');
    const tempDir = process.env.TEMP || path.join(localAppData, 'Temp');

    // 1. Windows User Temp
    this.register(
      new BaseCleanupRule(
        'WINDOWS_USER_TEMP',
        1,
        'Windows User Temp Files',
        'SYSTEM',
        'SAFE',
        true,
        false,
        'NONE',
        false,
        () => [tempDir],
        {
          whyItExists: 'Temporary files created by running Windows applications and installers.',
          consequenceOfRemoval: 'Applications may recreate temp files as needed. Inactive scratch files are cleared.',
          potentialImpact: 'No impact on source code or configuration. Frees up immediate storage.',
          safetyConfidence: 'SAFE'
        },
        undefined,
        'system'
      )
    );

    // 2. Windows Crash Dumps
    this.register(
      new BaseCleanupRule(
        'WINDOWS_CRASH_DUMPS',
        1,
        'Application Crash Dumps',
        'SYSTEM',
        'SAFE',
        true,
        false,
        'NONE',
        false,
        () => [path.join(localAppData, 'CrashDumps')],
        {
          whyItExists: 'Generated by Windows Error Reporting when an application crashes.',
          consequenceOfRemoval: 'Removes post-mortem memory dump files (.dmp).',
          potentialImpact: 'Historic diagnostic dumps for past crashes will be lost.',
          safetyConfidence: 'SAFE'
        },
        undefined,
        'system'
      )
    );

    // 3. npm Cache
    this.register(
      new BaseCleanupRule(
        'NODE_NPM_CACHE',
        1,
        'npm Package Cache',
        'NODE',
        'REBUILDABLE',
        true,
        false,
        'MEDIUM',
        true,
        () => [
          path.join(localAppData, 'npm-cache'),
          path.join(appData, 'npm-cache')
        ],
        {
          whyItExists: 'Tarballs and index metadata cached by npm to accelerate installs.',
          consequenceOfRemoval: 'Cleans the local cache. Future npm installs will redownload tarballs from registry.',
          potentialImpact: 'Next npm install command may take longer and require active network connection.',
          safetyConfidence: 'REBUILDABLE'
        },
        'Future npm installs will re-fetch packages from the npm registry.',
        'npm',
        ['node']
      )
    );

    // 4. pnpm Store
    this.register(
      new BaseCleanupRule(
        'NODE_PNPM_STORE',
        1,
        'pnpm Global Store',
        'NODE',
        'REBUILDABLE',
        false,
        false,
        'HIGH',
        true,
        () => [path.join(localAppData, 'pnpm', 'store')],
        {
          whyItExists: 'Content-addressable package storage shared by projects using pnpm.',
          consequenceOfRemoval: 'Removes cached files. Existing hardlinks remain intact; new installs will re-fetch.',
          potentialImpact: 'Subsequent pnpm install runs will download packages again.',
          safetyConfidence: 'REBUILDABLE'
        },
        'Rebuilding packages in projects using pnpm may require network re-download.',
        'pnpm',
        ['node']
      )
    );

    // 5. Yarn Cache
    this.register(
      new BaseCleanupRule(
        'NODE_YARN_CACHE',
        1,
        'Yarn Cache',
        'NODE',
        'REBUILDABLE',
        true,
        false,
        'MEDIUM',
        true,
        () => [path.join(localAppData, 'Yarn', 'Cache')],
        {
          whyItExists: 'Downloaded package tarballs cached across Yarn projects.',
          consequenceOfRemoval: 'Future yarn install runs will re-fetch packages from registry.',
          potentialImpact: 'First install after cleanup may take slightly longer.',
          safetyConfidence: 'REBUILDABLE'
        },
        undefined,
        'yarn',
        ['node']
      )
    );

    // 6. Gradle Caches
    this.register(
      new BaseCleanupRule(
        'GRADLE_CACHES',
        1,
        'Gradle Cache & Artifacts',
        'GRADLE',
        'REBUILDABLE',
        true,
        false,
        'HIGH',
        true,
        () => [path.join(userProfile, '.gradle', 'caches')],
        {
          whyItExists: 'Gradle stores downloaded plugins, dependencies, and execution cache.',
          consequenceOfRemoval: 'Removes old build artifact caches and jars.',
          potentialImpact: 'First Android or Java Gradle build after cleanup will re-download plugins and take longer.',
          safetyConfidence: 'REBUILDABLE'
        },
        'First Android/Java Gradle build may take longer and require internet connection.',
        'gradle',
        ['android-sdk']
      )
    );

    // 7. Flutter / Pub Cache
    this.register(
      new BaseCleanupRule(
        'FLUTTER_PUB_CACHE',
        1,
        'Flutter Pub Cache',
        'FLUTTER',
        'REBUILDABLE',
        true,
        false,
        'MEDIUM',
        true,
        () => [path.join(localAppData, 'Pub', 'Cache')],
        {
          whyItExists: 'Dart and Flutter packages downloaded from pub.dev.',
          consequenceOfRemoval: 'Pub cache will be cleared.',
          potentialImpact: 'Next flutter pub get will re-download packages from pub.dev.',
          safetyConfidence: 'REBUILDABLE'
        },
        undefined,
        'flutter'
      )
    );

    // 8. VS Code Cache
    this.register(
      new BaseCleanupRule(
        'VSCODE_CACHES',
        1,
        'VS Code Cached Data',
        'IDE',
        'REBUILDABLE',
        true,
        false,
        'LOW',
        false,
        () => [
          path.join(appData, 'Code', 'CachedData'),
          path.join(appData, 'Code', 'Cache')
        ],
        {
          whyItExists: 'V8 compilation caches and editor cached assets generated by VS Code.',
          consequenceOfRemoval: 'VS Code will regenerate caches transparently on next start.',
          potentialImpact: 'Editor launches seamlessly; no settings or extensions are affected.',
          safetyConfidence: 'REBUILDABLE'
        },
        undefined,
        'vscode'
      )
    );
  }

  public register(rule: CleanupRule): void {
    this.rules.set(rule.id, rule);
  }

  public getRule(id: string): CleanupRule | undefined {
    return this.rules.get(id);
  }

  public getAllRules(): CleanupRule[] {
    return Array.from(this.rules.values());
  }

  public getRulesByCategory(category: CleanupRule['category']): CleanupRule[] {
    return this.getAllRules().filter(r => r.category === category);
  }
}
