import { SafetyLevel, ToolchainId } from './rules.types.js';

export interface SafetyExplanation {
  label: string;
  shortDescription: string;
  detailedDescription: string;
}

export interface ToolchainExplanation {
  id: ToolchainId;
  displayName: string;
  summary: string;
  whyBelongs: string;
  ecosystem: string;
}

/**
 * Authoritative documentation registry for SafetyLevel classifications.
 * Describes the classification criteria without altering SafetyEngine evaluation logic.
 */
export const SAFETY_EXPLANATIONS: Record<SafetyLevel, SafetyExplanation> = {
  SAFE: {
    label: 'Safe',
    shortDescription: 'Can be removed and regenerated automatically.',
    detailedDescription:
      'Low-risk ephemeral cache or temporary data that development tools recreate automatically as needed during normal operation without manual reconfiguration.'
  },
  REBUILDABLE: {
    label: 'Rebuildable',
    shortDescription: 'Generated cache/data that development tools can recreate.',
    detailedDescription:
      'Intermediate build outputs, compilation artifacts, or downloaded package archives. Development tools can recreate them, but rebuilding or reinstalling may temporarily take longer.'
  },
  REVIEW: {
    label: 'Review',
    shortDescription: 'Removal may affect local state or require additional consideration.',
    detailedDescription:
      'Historical logs, crash telemetry, or environment-specific caches. May contain diagnostic information or local state; inspect before removal if actively troubleshooting.'
  },
  PROTECTED: {
    label: 'Protected',
    shortDescription: 'DevSweep will never allow this item to be selected.',
    detailedDescription:
      'Source code directories (.git), environment keys (.env), user documents, or operating system essentials safeguarded by DevSweep invariants to prevent accidental data loss.'
  }
};

/**
 * Authoritative documentation registry for ToolchainId attribution.
 * Explains why an item belongs to a toolchain without creating shadow heuristics.
 */
export const TOOLCHAIN_EXPLANATIONS: Record<ToolchainId, ToolchainExplanation> = {
  node: {
    id: 'node',
    displayName: 'Node.js',
    summary: 'JavaScript runtime environment',
    whyBelongs:
      'Core Node.js runtime caches and global package assets used for executing and building JavaScript and TypeScript applications.',
    ecosystem: 'JavaScript / TypeScript'
  },
  npm: {
    id: 'npm',
    displayName: 'npm',
    summary: 'Node Package Manager',
    whyBelongs:
      'Global tarball cache and HTTP response cache maintained by npm for Node.js package resolution.',
    ecosystem: 'Node.js'
  },
  pnpm: {
    id: 'pnpm',
    displayName: 'pnpm',
    summary: 'Fast, disk space efficient package manager',
    whyBelongs:
      'Global content-addressable storage where downloaded package files are preserved and hard-linked across Node.js projects.',
    ecosystem: 'Node.js'
  },
  yarn: {
    id: 'yarn',
    displayName: 'Yarn',
    summary: 'Yarn package manager',
    whyBelongs:
      'Offline mirror and global cache directory storing downloaded package archives for Yarn projects.',
    ecosystem: 'Node.js'
  },
  flutter: {
    id: 'flutter',
    displayName: 'Flutter',
    summary: 'Multi-platform UI toolkit & Dart SDK',
    whyBelongs:
      'Hosted package archives, git dependency checkouts, and build artifacts managed by Flutter and Dart pub.',
    ecosystem: 'Dart / Flutter'
  },
  gradle: {
    id: 'gradle',
    displayName: 'Gradle',
    summary: 'Build automation tool',
    whyBelongs:
      'Downloaded dependency JARs, wrapper distributions, and compiler transformation caches generated by Gradle.',
    ecosystem: 'Java / Kotlin / Android'
  },
  'android-sdk': {
    id: 'android-sdk',
    displayName: 'Android SDK',
    summary: 'Android developer platform tools',
    whyBelongs:
      'Build-tools caches, platform system images, and emulator temporary data generated during Android development.',
    ecosystem: 'Android'
  },
  vscode: {
    id: 'vscode',
    displayName: 'VS Code',
    summary: 'Visual Studio Code editor',
    whyBelongs:
      'Workspace storage cache, extension download archives, GPU cache, and code intelligence indexes created by VS Code.',
    ecosystem: 'Developer Tooling'
  },
  git: {
    id: 'git',
    displayName: 'Git',
    summary: 'Distributed version control system',
    whyBelongs:
      'Temporary pack files, reflogs, and local repository staging caches managed by Git.',
    ecosystem: 'Version Control'
  },
  docker: {
    id: 'docker',
    displayName: 'Docker',
    summary: 'Containerization platform',
    whyBelongs:
      'Dangling image layers, builder cache, and container runtime logs created by Docker Desktop.',
    ecosystem: 'Containers'
  },
  system: {
    id: 'system',
    displayName: 'System',
    summary: 'Windows developer system caches',
    whyBelongs:
      'Windows developer temp directories, crash telemetry dumps, and system-level developer workfiles.',
    ecosystem: 'Windows OS'
  }
};

/**
 * Retrieves authoritative safety level documentation.
 * Strongly typed: guarantees valid explanation for any canonical SafetyLevel.
 */
export function getSafetyExplanation(level: SafetyLevel): SafetyExplanation {
  const explanation = SAFETY_EXPLANATIONS[level];
  if (explanation) return explanation;

  // Runtime fallback for untrusted inputs without guessing
  return {
    label: 'Unknown',
    shortDescription: 'Classification is unknown.',
    detailedDescription: 'No authoritative safety explanation is registered for this classification level.'
  };
}

/**
 * Retrieves authoritative toolchain attribution documentation.
 * Strongly typed: guarantees valid explanation for any canonical ToolchainId.
 */
export function getToolchainExplanation(id: ToolchainId): ToolchainExplanation {
  const explanation = TOOLCHAIN_EXPLANATIONS[id];
  if (explanation) return explanation;

  // Runtime fallback for untrusted inputs without guessing
  return {
    id: (id || 'system') as ToolchainId,
    displayName: 'Unknown toolchain',
    summary: 'Unattributed developer tooling',
    whyBelongs: 'No toolchain attribution is available for this item.',
    ecosystem: 'Unknown'
  };
}

/**
 * Formats a composite attribution combining primary toolchain and any directional related toolchains.
 */
export interface ToolchainAttribution {
  primary: ToolchainExplanation;
  related: ToolchainExplanation[];
}

export function getToolchainAttribution(
  primaryId?: ToolchainId,
  relatedIds?: ToolchainId[]
): ToolchainAttribution | null {
  if (!primaryId) return null;

  const primary = getToolchainExplanation(primaryId);
  const related = (relatedIds || [])
    .filter((id) => id !== primaryId)
    .map((id) => getToolchainExplanation(id));

  return { primary, related };
}
